[finance_api_params]
period = "1y" # Time period for which data is being fetched
tickers = [
    "AAPL",
    "LLY",
    "JPM",
    "AMZN",
    "XOM",
    "WMT",
    "GOOGL",
    "CAT",
    "LIN",
    "NEE",
]
